spring:
  application:
    name: lionproject2-backend

  threads:
    virtual:
      enabled: true 


portone:
  # 1. 포트원 가맹점 식별코드 (imp로 시작하는 고유 번호)
  imp-code: "imp71320015" 
  
  # 2. 포트원 REST API 키 (포트원 콘솔에서 복사)
  api-key: "3265177685842072"
  
  api-secret: "yGE2ckoLpUqvtd4m4DiJvCinCTjmbPVQL5H6xsEBkvVUKVMOB1lj9WMBw0VjXvkNFYo8o7ggjKAFcuHS"

payment:
  inicis:
    mid: "INIpaytest"
    
    # 웹결제 필수 signkey (테스트용 공용키)
    signkey: "SU5JTElURV9URVNUX1NJR05LRVk="
    
    # 이니시스 전용 API 인증 정보 (제공해주신 IV 값 포함)
    ini-api-key: "test" # 테스트시 보통 test 입력
    ini-api-iv: "HYb3yQ4f65QL89==" 



#*db넣어야함